### PR TITLE
better (?) string concatenation

### PR DESCRIPTION
**Pull request by 343max**
For reasons that I don’t fully understand the code wouldn’t compile on my Xcode 8.3 because of an “Ambiguous reference to member ‘+’” error in line 52.

I wonder if this is a bug in the current swift release.

So I rewrote the code a bit to join an array instead to create a multiline string. Hope you don’t mind.

Great project! Do you plan to implement full HyperCard support? Do you need any help? :)

### CODE REVIEW

**Comment by PierreLorenzi** [comment]
Thank you very much for your commits! I appreciate.

Sadly I don't plan to implement full HyperCard support, because

- it would be long. For example it requires text editing, script parsing (complex and very tricky, though people from [PXI](https://sourceforge.net/projects/pxi/) already did it).

- there is no more active development in HyperCard, I just made this soft to see the stacks.

- the stacks would be changed, so they'd have to be saved a new format, that would be weird. We can't use the current format because we don't know it yet enough to make editions safely, to the data as well as to the resource forks.

I had only thought on some little things to improve the experience, like, for every stack, displaying a list of the resources, displaying the patterns, making a Cover-Flow like navigation, and, to have a bit of fun, letting the user move between cards with the old-fashion visual effects (to be selected from a menu).

But I'm not sure to make any update. At least in the next days I will correct the compilation chain (the release is not automated for the moment).

**Comment by 343max** [comment]
Back in the day I learned programming using HyperCard and I still have fond memories. For years I wanted to reinvent HyperCard for the internet age. Guess it might be fun to implement a bit more functionality.

**Comment by mstevenson** [comment]
For a reimplementation of the HyperCard editor, I'd recommend looking at [StackSmith](https://github.com/uliwitness/Stacksmith).

**Comment by PierreLorenzi** [comment]
Yeah, there's the list of the HyperCard clones at hypercard.org.

You can make up your mind.

**Pull request merged**
